# Generated by Django 5.0.2 on 2024-02-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docente',
            options={'verbose_name': 'docente', 'verbose_name_plural': 'docentes'},
        ),
    ]
