# Generated by Django 5.0.2 on 2024-02-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_alter_docente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docente',
            options={},
        ),
    ]
