# Generated by Django 5.0.2 on 2024-02-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0003_alter_docente_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='materia',
            new_name='materiaD',
        ),
    ]
