# Generated by Django 5.0.2 on 2024-02-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='created',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='id',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='image',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='updated',
        ),
        migrations.AddField(
            model_name='curso',
            name='codigo',
            field=models.CharField(default=0, max_length=3, primary_key=True, serialize=False),
        ),
    ]
