# Generated by Django 5.0.2 on 2024-02-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_curso_created_remove_curso_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
