# Generated by Django 5.0.2 on 2024-02-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'estudiante', 'verbose_name_plural': 'estudiantes'},
        ),
    ]
