# Generated by Django 5.0.2 on 2024-02-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_alter_estudiante_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={},
        ),
    ]
