# Generated by Django 5.0.2 on 2024-02-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_alter_estudiante_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='materia',
            new_name='materiaE',
        ),
    ]
